<?php
declare(strict_types=1);
namespace ShadowShinobi\Combat;
use InvalidArgumentException;
final class CombatEngine
{
    public const VERSION='0.1.1';
    public static function start(array $allies,array $enemy):array{ $u=[]; foreach($allies as $i=>$r){$id='a'.($i+1);$u[$id]=self::unit($id,'ally',$r);} $u['e1']=self::unit('e1','enemy',$enemy); $s=['version'=>self::VERSION,'round'=>1,'active_id'=>null,'status'=>'active','phase'=>'opening','units'=>$u,'events'=>[]]; self::next($s); self::event($s,'battle_start',['message'=>'The ruined shrine exhales ash. The hunt begins.']); return $s; }
    public static function act(array $s,string $actorId,string $action):array{
        if(($s['status']??'')!=='active'||($s['active_id']??'')!==$actorId)throw new InvalidArgumentException('Invalid turn.');
        if(($s['units'][$actorId]['side']??'')!=='ally')throw new InvalidArgumentException('Only ally turns accept actions.');
        if(!in_array($action,['quick','shadow','guard','signature'],true))throw new InvalidArgumentException('Unknown action.');
        $enemy=self::enemy($s);if(!$enemy)return $s;$actor=&$s['units'][$actorId];$before=count($s['events']);
        if($action==='guard'){$actor['guard']=true;$actor['energy']=min($actor['max_energy'],$actor['energy']+10);self::event($s,'guard',['actor'=>$actorId]);}
        else{$base=0;$label='Quick Strike';$crit=.12;if($action==='shadow'){if($actor['energy']<25)throw new InvalidArgumentException('Not enough essence.');$actor['energy']-=25;$base=random_int(38,58)+(int)floor($actor['skill_power']*.38);$label='Shadow Art';$crit=.22;}elseif($action==='signature'){if($actor['energy']<100)throw new InvalidArgumentException('Signature requires 100 essence.');if($s['units'][$enemy]['hp']/$s['units'][$enemy]['max_hp']>.35)throw new InvalidArgumentException('Crimson Sever requires the target below 35%.');$actor['energy']=0;$base=random_int(115,165)+(int)floor($actor['skill_power']*.72);$label='Crimson Sever';$crit=.35;}else{$base=random_int(24,40)+(int)floor($actor['attack']*.20);}self::damage($s,$actorId,$enemy,$base,$crit,$label,$action==='signature');if($action==='shadow'&&$s['units'][$enemy]['hp']>0&&random_int(1,100)<=55){$s['units'][$enemy]['bleed']=min(3,(int)($s['units'][$enemy]['bleed']??0)+1);self::event($s,'status',['target'=>$enemy,'status'=>'bleed','stacks'=>$s['units'][$enemy]['bleed']]);}}
        if(($s['units'][$enemy]['hp']??0)<=0){$s['status']='victory';$s['phase']='result';self::event($s,'battle_end',['result'=>'victory','message'=>'The Wraith collapses into the ash.']);}
        else{self::bleed($s);self::next($s);}
        $s['events_tail']=array_slice($s['events'],$before);return $s;
    }
    private static function unit(string $id,string $side,array $r):array{$hp=max(1,(int)($r['health']??500));$e=max(100,(int)($r['essence_capacity']??100));return['id'=>$id,'side'=>$side,'name'=>(string)($r['name']??'Wraith'),'class'=>(string)($r['class_name']??'Combatant'),'role'=>(string)($r['role_name']??'Combatant'),'level'=>max(1,(int)($r['level']??1)),'hp'=>$hp,'max_hp'=>$hp,'attack'=>max(1,(int)($r['attack']??50)),'defense'=>max(0,(int)($r['defense']??20)),'speed'=>max(1,(int)($r['speed']??20)),'skill_power'=>max(1,(int)($r['skill_power']??25)),'critical_rate'=>(float)($r['critical_rate']??5),'critical_damage'=>(float)($r['critical_damage']??150),'energy'=>$side==='enemy'?$e:$e,'max_energy'=>$e,'guard'=>false,'bleed'=>0];}
    private static function damage(array &$s,string $a,string $t,int $base,float $crit,string $label,bool $finish=false):void{$u=$s['units'][$a];$v=&$s['units'][$t];$mit=max(.55,1-$v['defense']/($v['defense']+180));$d=max(1,(int)floor($base*$mit));$isCrit=random_int(1,10000)<=round(max($crit,$u['critical_rate']/100)*10000);if($isCrit)$d=max($d+1,(int)floor($d*$u['critical_damage']/100));$v['hp']=max(0,$v['hp']-$d);self::event($s,'damage',['actor'=>$a,'target'=>$t,'amount'=>$d,'critical'=>$isCrit,'finisher'=>$finish,'label'=>$label,'remaining_hp'=>$v['hp']]);if($isCrit)self::event($s,'impact',['type'=>'critical','target'=>$t]);if($finish&&$v['hp']<=0)self::event($s,'finisher',['target'=>$t,'label'=>$label]);}
    private static function enemyAttack(array &$s,string $id):void{$targets=array_filter($s['units'],fn($u)=>$u['side']==='ally'&&$u['hp']>0);if(!$targets){$s['status']='defeat';$s['phase']='result';self::event($s,'battle_end',['result'=>'defeat','message'=>'The cell is broken.']);return;}uasort($targets,fn($x,$y)=>$x['hp']<=>$y['hp']);$t=(string)array_key_first($targets);$v=&$s['units'][$t];$e=$s['units'][$id];$d=max(1,(int)floor((random_int(22,36)+(int)floor($e['attack']*.18))*max(.55,1-$v['defense']/($v['defense']+180))));if($v['guard']){$d=max(1,(int)floor($d*.42));$v['guard']=false;} $v['hp']=max(0,$v['hp']-$d);self::event($s,'enemy_attack',['actor'=>$id,'target'=>$t,'amount'=>$d,'remaining_hp'=>$v['hp'],'label'=>'Wraith Counterattack']);if($v['hp']<=0)self::event($s,'defeated',['target'=>$t]);}
    private static function bleed(array &$s):void{foreach($s['units'] as $id=>&$u){$n=(int)($u['bleed']??0);if($n>0&&$u['hp']>0){$d=min($u['hp'],7*$n);$u['hp']-=$d;$u['bleed']=$n-1;self::event($s,'bleed_tick',['target'=>$id,'amount'=>$d,'remaining_hp'=>$u['hp']]);}}unset($u);}
    private static function next(array &$s):void{$living=array_filter($s['units'],fn($u)=>$u['hp']>0);if(!$living){$s['status']='defeat';$s['phase']='result';return;}uasort($living,fn($a,$b)=>$a['speed']===$b['speed']?strcmp($a['id'],$b['id']):$b['speed']<=>$a['speed']);$s['active_id']=(string)array_key_first($living);$s['round']++;$actor=$s['units'][$s['active_id']];if($actor['side']==='enemy'){ $s['phase']='enemy';self::enemyAttack($s,$s['active_id']);if($s['status']==='active')self::next($s); } else {$s['phase']='player';foreach($s['units'] as &$u)$u['energy']=min($u['max_energy'],$u['energy']+8);unset($u);}}
    private static function enemy(array $s):?string{foreach($s['units'] as $id=>$u)if($u['side']==='enemy'&&$u['hp']>0)return$id;return null;}
    private static function event(array &$s,string $type,array $data):void{$s['events'][]=['type'=>$type,'at'=>microtime(true),'data'=>$data];}
}
